In [1]:
import pandas as pd

In [4]:
path='/content/employee_data_5000.xlsx'
df=pd.read_excel(path)

In [5]:
#View first 10 rows
df.head(10)

   Employee_ID    Name Department   Salary
0          498   Arjun    Finance  35425.0
1         4383    Amit         IT  77374.0
2         2312   Karan  Marketing  77585.0
3          551    Amit  Marketing  91250.0
4         2098   Karan         HR  98855.0
5         1167    Amit  Marketing  40573.0
6         2150   Meena  Marketing  61760.0
7          104  Simran      Sales  96129.0
8           18    Neha      Sales  52897.0
9         2161   Priya         HR  29273.0

In [7]:
#view last 10 rows
df.tail(10)

      Employee_ID   Name Department   Salary
4990          428   Ravi         IT  33608.0
4991         3050  Meena         HR  42036.0
4992         1264  Priya    Finance  57475.0
4993         1440   Amit    Finance  81822.0
4994         4241   Amit         HR      NaN
4995         2767   Neha  Marketing  54633.0
4996         2732  Priya  Marketing  44593.0
4997         3343  Meena         HR  30961.0
4998         3622   Amit  Marketing  65862.0
4999         1671    NaN         HR  63796.0

In [8]:
#Summary of DataFrame (data types, nulls)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  5000 non-null   int64
 1   Name         4770 non-null   object
 2   Department   4732 non-null   object
 3   Salary       4764 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 156.4+ KB

In [9]:
#statistical summary
df.describe()

       Employee_ID        Salary
count  5000.000000   4764.000000
mean   2398.142600  60341.140848
std    1387.638187  23033.266789
min       1.000000  20021.000000
25%    1194.750000  40678.250000
50%    2398.500000  60591.000000
75%    3595.250000  80444.500000
max    4800.000000  99982.000000

In [11]:
#Get column names
df.columns

Index(['Employee_ID', 'Name', 'Department', 'Salary'], dtype='object')

In [14]:
#Find duplicate rows
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

In [16]:
#Detect missing values
df.isnull()

      Employee_ID   Name  Department  Salary
0           False  False       False   False
1           False  False       False   False
2           False  False       False   False
3           False  False       False   False
4           False  False       False   False
...           ...    ...         ...     ...
4995        False  False       False   False
4996        False  False       False   False
4997        False  False       False   False
4998        False  False       False   False
4999        False   True       False   False

[5000 rows x 4 columns]

In [20]:
#with null check
df.isnull().sum()

Employee_ID      0
Name           230
Department     268
Salary         236
dtype: int64

In [23]:
#Fill missing values
df.fillna(0, inplace=True)

In [22]:
#Remove missing values
df.dropna()

      Employee_ID   Name Department   Salary
0             498  Arjun    Finance  35425.0
1            4383   Amit         IT  77374.0
2            2312  Karan  Marketing  77585.0
3             551   Amit  Marketing  91250.0
4            2098  Karan         HR  98855.0
...           ...    ...        ...      ...
4995         2767   Neha  Marketing  54633.0
4996         2732  Priya  Marketing  44593.0
4997         3343  Meena         HR  30961.0
4998         3622   Amit  Marketing  65862.0
4999         1671      0         HR  63796.0

[5000 rows x 4 columns]